### ISSUE TITLE
Increase the usage of compound assignment operators

### ISSUE THREAD

**Issue by elfring** [trackmate-sc/TrackMate#204]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of compound operators](https://docs.oracle.com/javase/specs/jls/se17/html/jls-15.html#jls-15.26 "Description for assignment operators") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal$ perl -p -i.orig -0777 -e 's#\b(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-*/%^]|&(?!&)|\|(?!\|)|<<|>>>?)#$+{target} $+{operator}=#gm' $(find ~/Projekte/TrackMate/lokal -name '*.java')
```

:crystal_ball: How will development interests evolve further also according to update candidates in 142 lines of this software?

**Comment by tinevez** [comment]
Hello @elfring 
I don't know what this could bring. Could you ellaborate?

**Comment by elfring** [comment]
:thought_balloon: I suggest to take another look at consequences according to [the following information from the Java language specification](https://docs.oracle.com/javase/specs/jls/se18/html/jls-15.html#jls-15.26.2 "Description for compound assignment operators").

“…
A compound assignment expression of the form `E1 op= E2` is equivalent to `E1 = (T) ((E1) op (E2))`, where `T` is the type of `E1`, except that `E1` is evaluated only once.
…”

**Comment by tinevez** [comment]
Sorry @elfring I did not see how to fit this in the current dev roadmap.

**Comment by tinevez** [comment]
Sorry if I sounded rude  I did not mean it. 
I did not understand the rationale behind the changes you proposed, the reasons behind and what they would bring. 
If you feel it is important maybe I could suggest to make a fork, run the changes and measure some metrics that demonstrate the benefit of the changes.
What do you think?

**Comment by elfring** [comment]
>I did not understand the rationale behind the changes you proposed, the reasons behind and what they would bring.

Do you find the referenced information from the Java language specification still unclear?
