### ISSUE TITLE
LabeImageDetectorFactory should be LabelImageDetectorFactory

### ISSUE THREAD

**Issue by JonathanCSmith** [trackmate-sc/TrackMate#235]
Typo in this detector factory - quick scan seems correct, but due to fonts, the 'L' is actually an 'I'. This threw me for a loop when trying to diagnose an import issue.

**Comment by tinevez** [comment]
I know of it, my shame.
I am delaying fixing it because it will break other modules and many scripts. 
But anyway the next update will include a refactoring of the tracking part, and will  be breaking changes. So I will fix it then.
