### ISSUE TITLE
Correct Env to run ExampleScript_1.py 

### ISSUE THREAD

**Issue by SVBPE** [trackmate-sc/TrackMate#239]
Hallo,

I am trying to run your script "ExampleScript_1.py", but I cannot manage to make the header with the imports work.

For prior automation of Fiji Tasks I used the Python wrapper for ImageJ2 (https://github.com/imagej/pyimagej), where you initialize Fiji with the following: 
        import imagej
        ij = imagej.init(...)

The Error I get when I want to run your example is:
      "could not find javascript engine"
      "No module named 'ij"

Which env do you use? 

In general I want to run a script that loops over a dataset of stained nuclei with fixed Trackmate settings. Since the Fiji recorder is not giving out any specific settings made during the setup in the GUI, I want to access the developer mode. 

Thank you very much for your help!

Best,
Stefan

**Comment by tinevez** [comment]
Hello @SVBPE 

Actually these scripts only work within the Jython interpreter of Fiji. They are not expected to work in another env, yet.
