### ISSUE TITLE
"All spots" table export for TrackMate Batcher

### ISSUE THREAD

**Issue by maxadrian** [trackmate-sc/TrackMate#241]
The TrackMate batcher currently exports the results table from the tracks. It would be great if it could also have an extra option to export the "All spots table" that contains the localization data of spots that are not part of tracks.
Thanks for all the fantastic work on TrackMate!

**Comment by tinevez** [comment]
Reopen in the right repo

**Comment by tinevez** [comment]
Done in the right repo.
