### ISSUE TITLE
Trackmate SpotsID initial value

### ISSUE THREAD

**Issue by manerotoni** [trackmate-sc/TrackMate#243]
I encountered following issues with the numbering of spotsID

* spotsID on the first frame do not start with ID0001. This is true for different detectors.
* The value of the smallest spotsID incrementally increases when trackmate is restarted. The value increases by the number of spots found in the previous round.
* For many spots we easily reach the 16bit limit in case we need to generate a labeled image as output and do not want to restart imageJ every time.
* Export the label image creates labels with an offset of 1. SpotID 2000 has a label 2001. This is a little confusing and not really necessary.

See also entry in forum.sc https://forum.image.sc/t/trackmate-spotsid-initial-value/76753

**Comment by tinevez** [comment]
Hello @manerotoni 
Yes, this is the expected behavior. The ID will increase continuously within a Fiji session.
Also the label ID is also the expected behavior. We want to reserve the label 0 for the background, even if a spot has an ID of 0.
I do not know how to solve the issue with 16-bit limit....

**Comment by manerotoni** [comment]
Thanks, I guess we need to restart Fiji at every round, but still use this very nice and useful tool. 

`Also the label ID is also the expected behavior. We want to reserve the label 0 for the background, even if a spot has an ID of 0.`

I understand this, but the initial spotsID after a fresh restart in Fiji starts with >=2000. This is what I meant "unnecessary" as we are already far above 0.

**Comment by tinevez** [comment]
Hello @manerotoni 
Is this issue still valid? Can I close it?

**Comment by manerotoni** [comment]
Hello @tinevez,
thanks for asking. In my opinion the issue is still open  (trackmate version 7.10.2).  I am not sure if I am the only one that has a problem with it. 

Using the example data I get a starting value of a spot ID of 2048 ending at 2207. Starting again trackmate gives an initial spot ID of 2439. 

If you run trackmate via a script on several movies or for long movies you quickly reaches a point where the maximal number of spots ID in a 16bit labeled image is reached and you get non-sense results. Also the fact that the counting of the first spot does not starts at 1 but with a rather high and not so reproducible value is an issue when porting the labels to another software.
