### ISSUE TITLE
Bug: xml file doesn't open

### ISSUE THREAD

**Issue by xlaub** [trackmate-sc/TrackMate#244]
I found out why my xml files don't open after saving a TrackMate session.

For example my file is called: 'bead on filopodium.tif'
The resulting xml file that is created is then called: 'beadonfilopodium.tif'
Somehow the spaces are cut out. (I'm using Windows 10, don't know if this is OS specific)

But in the xml file the path is written as  '...\bead on filopodium.tif'

So it won't open unless I rename the xml file accordingly: 'bead on filopodium.xml'

Best regards

**Comment by tinevez** [comment]
Hello. Could you elaborate a bit please? 
I am a bit confused about the TIF vs XML. Do you mean that TrackMate does not find the TIF file? Or crashes when trying to open the XML file?

**Comment by xlaub** [comment]
Thanks for your reply.
Hm, I don't remember the exact error. I think it said it cannot open the xml file. or doesn't find it.
Don't know what happened. I tried to reproduce the error, but now it works fine.

Maybe the problem was that I was not saving the file before doing the tracking. 
I will see if I get this problem again and post what's happening. 

Thanks anyway :)

**Comment by tinevez** [comment]
Excellent!
