### ISSUE TITLE
Possibility to have 32 bit label image ? 

### ISSUE THREAD

**Issue by lguerard** [trackmate-sc/TrackMate#267]
Hi !

I encountered the issue today of having more than 65536 labels in an image but TrackMate exported a 16bit image still. I looked for it and found this part.

https://github.com/trackmate-sc/TrackMate/blob/90544a7b590e4108d8d8717630d1fe87de6ea70b/src/main/java/fiji/plugin/trackmate/action/LabelImgExporter.java#LL438C2-L446C3

I was thinking of changing to `UnsignedLongType` instead if the number of spots were above that value, would that be the smart way or do you think of any reason why it wouldn't work ?

Thanks !

**Comment by tinevez** [comment]
I think they would not be displayed correctly in ImageJ.
I need to test this.

**Comment by tinevez** [comment]
I see that using a 32-bit float image to represents labels would work.
Here: 

https://en.wikipedia.org/wiki/Single-precision_floating-point_format#Precision_limitations_on_integer_values

it is said that we can represent integers up to 16M exactly on such a pixel type. Definitely an improvement over the 65536 limit.

I will work on this.

**Comment by tinevez** [comment]
Or do you feel like working on it?

**Comment by lguerard** [comment]
Hi !

Thanks for still looking into it, highly appreciated ! :) 

I'd be happy to work on it, but I'm really unfamiliar with all the types of variables and what would be the best way to achieve this. If you have some pointers, I could still try. If you think it's faster if you do it, that's also good. Let me know what I can do to help !

**Comment by ctrueden** [comment]
You can construct a signed 32-bit integer image in ImageJ. Here is a Groovy example:
```groovy
import ij.process.IntProcessor
import ij.IJ
import ij.ImagePlus

size = 800;
n = size*size;
ip = new IntProcessor(size,size);
range = (long) (2 ** 32)
println(range)

for (var i=0; i<n; i++) {
  value = Integer.MIN_VALUE + (int) (i*range/n);
  if (i < 10) println(value);
  ip.set(i, value);
}
img = new ImagePlus("32-bit int image",ip);
img.getProcessor().resetMinAndMax();
IJ.run(img,"Viridis","");
img.show();
```

**Comment by ctrueden** [comment]
I'm reopening this for the moment, because the merged work that @tinevez did only enables float32 labelings, not int32 labelings. However, we could close this issue in favor of a new one—or maybe not even bother with a new issue until labelings with more than 16M labels become needed by someone. What do you think, @tinevez?

**Comment by tinevez** [comment]
Yes, let's make an issue when someone actually reports a problem.
