### ISSUE TITLE
NullPointerException on loading TrackMate .xml file, that exported by headless Groovy script

### ISSUE THREAD

**Issue by hzqfox** [trackmate-sc/TrackMate#275]
Loading error on the TrackMate xml file exported by the headless Groovy script.
The xml file exported also looks different from the one exported from within TrackMate plugin run.

The error message from Fiji:
java.lang.NullPointerException
	at fiji.plugin.trackmate.io.TmXmlReader.getVersion(TmXmlReader.java:520)
	at fiji.plugin.trackmate.LoadTrackMatePlugIn.run(LoadTrackMatePlugIn.java:105)
	at ij.IJ.runUserPlugIn(IJ.java:237)
	at ij.IJ.runPlugIn(IJ.java:203)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:748)

**Comment by tinevez** [comment]
Hello @hzqfox 
Funny it fails on determining the version number. 
Can you post the XML file in question, as well as a link to the Groovy script?

**Comment by hzqfox** [comment]
[link to the Groovy script](https://github.com/trackmate-sc/TrackMate/blob/master/scripts/Run_TrackMate_Headless.groovy)

The XML file looks like the following (to attach the file here, I changed the extension to txt):
[FakeTracks.txt](https://github.com/trackmate-sc/TrackMate/files/12067175/FakeTracks.txt)

**Comment by tinevez** [comment]
Ah! But `ExportTracksToXML` does not do what you need. It converts the tracks into a simpler XML format, made to be read by other software in the context of the ISBI challenge. It does **not** generate a TrackMate file. 

For this you need to play with the TmXmlWriter class:
https://github.com/trackmate-sc/TrackMate/blob/master/src/main/java/fiji/plugin/trackmate/io/TmXmlWriter.java

The XML generated by this class can then be loaded in TrackMate.
