### ISSUE TITLE
the spot is filtered by a quality threshold

### ISSUE THREAD

**Issue by asincerity** [trackmate-sc/TrackMate#287]
I run the trackmate in the macro script as follow:
run('TrackMate', "use_gui=false "
		+ "display_results=false "
		+ "radius=2.5 "
		+ "threshold=10 "
		+ "subpixel=true "
		+ "median=false "
		+ "max_distance=2 "
		+ "max_gap_distance=2 "
		+ "max_frame_gap=2 "
		+ "save_to=[" + path + File.separator + name +"spots.xml] ");
Then, I read the spot.xml in the matlab as follow:
 [spotTable,~] = trackmateSpots(spotsPath, {'POSITION_X','POSITION_Y','POSITION_T','QUALITY' });
But I find the spots are filtered by a quality threshold. This value can be found in the .xml 
<SpotFilterCollection>
<Filter feature="QUALITY" value="52.064532295171475" isabove="true"/>
![image](https://github.com/trackmate-sc/TrackMate/assets/55196577/847a08f8-4bd7-48e5-8a22-a6408e5ac90f)
So, how can i change the value in the run('Trackmate',...).   What is the parameters that can be changed in the run('Trackmate',...).
Thank you for your patience

**Comment by tinevez** [comment]
Rmlml it looks like the macro reads and uses the last quality value defined as a threshold.
I can look into it to fix it, but I would be of the opinion of retiring the macro support. Thoughts?

**Comment by asincerity** [comment]
> Rmlml it looks like the macro reads and uses the last quality value defined as a threshold. I can look into it to fix it, but I would be of the opinion of retiring the macro support. Thoughts?

When I use trackmate in macro, what are the parameters that I can specify in run() and where should I look for trackmate's support documentation for macro?

**Comment by tinevez** [comment]
In the code so far:
https://github.com/trackmate-sc/TrackMate/blob/master/src/main/java/fiji/plugin/trackmate/TrackMateRunner.java

But I see it does not work for you.
I can look into it and try to fix it, but I would be really in favor of retiring the macro support. It is really limited, does not let you configure a detector nor a specific tracker, has no filter, has no export. I strongly recommend instead using Jython scripting: 
https://imagej.net/plugins/trackmate/scripting/scripting

**Comment by asincerity** [comment]
> In the code so far: https://github.com/trackmate-sc/TrackMate/blob/master/src/main/java/fiji/plugin/trackmate/TrackMateRunner.java
> 
> But I see it does not work for you. I can look into it and try to fix it, but I would be really in favor of retiring the macro support. It is really limited, does not let you configure a detector nor a specific tracker, has no filter, has no export. I strongly recommend instead using Jython scripting: https://imagej.net/plugins/trackmate/scripting/scripting

Thank you for your reply. 
I will try to use the Jython scripting.

**Comment by asincerity** [comment]
> > In the code so far: https://github.com/trackmate-sc/TrackMate/blob/master/src/main/java/fiji/plugin/trackmate/TrackMateRunner.java
> > But I see it does not work for you. I can look into it and try to fix it, but I would be really in favor of retiring the macro support. It is really limited, does not let you configure a detector nor a specific tracker, has no filter, has no export. I strongly recommend instead using Jython scripting: https://imagej.net/plugins/trackmate/scripting/scripting
> 
> Thank you for your reply. I will try to use the Jython scripting.

I am trying to use the jython code.  How can I append code for save the whole trackmate work including setting parameters, spots  and tracks. I think it is equal to the button in the GUI as following image:
![image](https://github.com/trackmate-sc/TrackMate/assets/55196577/ecfb1d10-c363-460b-a806-8b89907f9a66)
I found a similar code
But I guess this one only saves tracks or points, not the whole job. And this still seems to be in java.
![image](https://github.com/trackmate-sc/TrackMate/assets/55196577/be0c68da-e0ba-46f0-838c-2218e78161a1)

**Comment by tinevez** [comment]
Hello @asincerity 

You can use the TmXmlWriter class. It does what the 'save' button does.

**Comment by asincerity** [comment]
thankyou vcery much.it really help me.
