### ISSUE TITLE
spot feature SNR definition

### ISSUE THREAD

**Issue by asincerity** [trackmate-sc/TrackMate#304]
Hello, I would like to ask you about the following definition when trackmate calculates the signal-to-noise ratio of a point. And in fact, should the noise in the signal to noise ratio, be the standard deviation of the background ：Iout.  Maby  SNR = (Iin-Iout)/std out

![image](https://github.com/user-attachments/assets/25abda27-bc43-44a9-b233-043cafb38509)

**Comment by tinevez** [comment]
I could not find a consensus on the SNR definition. The definition you mention (with the SD taken in the background) is sometimes criticized as it underestimates the SNR values in the case of Poisson noise: 

For this kind of noise, that we encounter mostly in microscopy, the variance proportional to the number of photons emitted by objects. If we measure the SD in the background, we underestimate the SD and overestimate the SNR. 
If we measure the SNR inside the object, then we have a numerical value we can relate to the number of emitted photons:

If _P_ is the number of photons collected by a pixel (corrected for background) and _c_ the proportionality coefficient between the camera values and the number of photons we have:

SNR =Mean / SD = 𝑐 𝑃 / 𝑐 √𝑃 = √𝑃

(taken from Huygens website: https://svi.nl/Signal-to-Noise-Ratio )
