### ISSUE TITLE
Manual typing of spot and track filtering values

### ISSUE THREAD

**Issue by jpylvanainen** [trackmate-sc/TrackMate#306]
Hey @tinevez , 

As you know, we have been playing with TrackMate a lot. There is one feature that i would love to have. When filtering spots or tracks after tracking, there is no possibility to manually set the cut-off value. You can do something like this when using the Threshold detector. Could this feature be added at some point? Thanks :)
![Trackmate_filtering](https://github.com/user-attachments/assets/c5a89ca1-54e4-4263-ba8c-c72e5b6dce51)

**Comment by tinevez** [comment]
Yes there is.
Simply select the filter window until the threshold value is printed in red.
Then type a numerical value and wait 2 s.

**Comment by tinevez** [comment]
Does it work for you @jpylvanainen ? Can I close this issue?

**Comment by jpylvanainen** [comment]
Hi, sorry for the delay, yes this works. Pretty hidden feature though :D

Thanks!
Joanna
