### ISSUE TITLE
TrackMate to process many frames at once

### ISSUE THREAD

**Issue by akatav** [trackmate-sc/TrackMate#313]
So, I have some time lapse images. I understand TrackMate processes frames one by one sequentially. I'd like to process n frames, n being the frame rate of the microscope at once using TrackMate. Can the TrackMate frame processing loop be parallelized for this ? Please help me by pointing out exactly where this looping happens in the codebase?

**Comment by tinevez** [comment]
Actually some TrackMate algorithms of TrackMate process several frames at once already, in a multithreaded manner.
The best example is the LoG detector, that will process X frames at once, X being the number of threads you can define in Fiji (_Edit > Options > Memory & Threads..._. It is a good idea to set this number of threads to be half the number of threads you have on your computer.
